MODEL: #MODEL field
    framework: "RecognizerGCN" #Mandatory, indicate the type of network, associate to the 'paddlevideo/modeling/framework/' .
    backbone: #Mandatory, indicate the type of backbone, associate to the 'paddlevideo/modeling/backbones/' .
        name: "STGCN" #Mandatory, The name of backbone.
        dropout: 0.3
        manifold_mixup: True

    head:
        name: "STGCNHead" #Mandatory, indicate the type of head, associate to the 'paddlevideo/modeling/heads'
        num_classes: 30 #Optional, the number of classes to be classified.
        # ls_eps: 0.1
        loss_cfg: 
            name: "CrossEntropyLoss"


DATASET: #DATASET field
    batch_size: 32 #Mandatory, bacth size
    num_workers: 4 #Mandatory, the number of subprocess on each GPU.
    test_batch_size: 1
    test_num_workers: 0
    train:
        format: "SkeletonDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        file_path: "/home/aistudio/split_dataset/train_data.npy" #Mandatory, train data index file path
        label_path: "/home/aistudio/split_dataset/train_label.npy"
    valid:
        format: "SkeletonDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        file_path: "/home/aistudio/split_dataset/valid_data.npy" #Mandatory, valid data index file path
        label_path: "/home/aistudio/split_dataset/valid_label.npy"
    test:
        format: "SkeletonDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        file_path: "/home/aistudio/data/data117808/test_B_data.npy" #Mandatory, valid data index file path
        test_mode: True

PIPELINE: #PIPELINE field
    train: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
        sample:
            name: "AutoPadding"
            window_size: 350
        transform: #Mandotary, image transfrom operator
            # - SkeletonNorm:
            #         axis: 2
            - PoseCompact:
                    hw_ratio: 1
                    allow_imgpad: True
                    step: 1
            - Resize:
                    scale: [-1,64]
            - RandomResizedCrop:
                    area_range: [0.56,1.0]
            - Resize:
                scale: [64,64]
                keep_ratio: False
            - Flip: 
                flip_ratio: 0.5
            - Toskeleton:
            - Norm:
                shape: [64,64]
    valid: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
        sample:
            name: "AutoPadding"
            window_size: 350
        transform: #Mandotary, image transfrom operator
            # - SkeletonNorm:
            #         axis: 2
            - PoseCompact:
                    hw_ratio: 1
                    allow_imgpad: True
                    step: 1
            - Resize:
                    scale: [-1,64]
            - CenterCropkp:
                    crop_size: 64
            - Toskeleton:
            - Norm:
                shape: [64,64]
    test: #Mandatory, indicate the pipeline to deal with the validing data. associate to the 'paddlevideo/loader/pipelines/'
        sample:
            name: "AutoPadding"
            window_size: 350
        transform: #Mandotary, image transfrom operator
            # - SkeletonNorm:
            #         axis: 2
            - PoseCompact:
                hw_ratio: 1
                allow_imgpad: True
                step: 1
                label: False
            - Resize:
                    scale: [-1,64]
            - CenterCropkp:
                    crop_size: 64
            - Toskeleton:
            - Norm:
                shape: [64,64]
OPTIMIZER: #OPTIMIZER field
  name: 'Momentum'
  momentum: 0.9
  learning_rate:
    # name: 'CosineAnnealingDecay'
    # learning_rate: 0.05
    # T_max: 150
    iter_step: True
    name: 'CustomWarmupCosineDecay'
    max_epoch: 80
    warmup_epochs: 10
    warmup_start_lr: 0.005
    cosine_base_lr: 0.05
  weight_decay:
    name: 'L2'
    value: 1e-4

# MIX:
#    name: "Mixup"
#    alpha: 0.2

METRIC:
    name: 'SkeletonMetric'
    out_file: 'prediction.csv'

INFERENCE:
    name: 'STGCN_Inference_helper'
    num_channels: 2
    window_size: 350
    vertex_nums: 25
    person_nums: 1


model_name: "STGCN-Joint"
log_interval: 10 #Optional, the interal of logger, default:10
epochs: 80 #Mandatory, total epoch
save_interval: 20